### ISSUE TITLE
Docker syslog driver and fluentd syslog source

### ISSUE THREAD

**Issue by superdump** [fluent/fluentd-docker-image#14]
How can one use the docker syslog driver with this fluentd container when using the syslog source?

**Comment by tagomoris** [comment]
Use `type syslog`
http://docs.fluentd.org/articles/in_syslog

**Comment by superdump** [comment]
Yes, but doesn't one need to use the host machine ip or something?

**Comment by viztastic** [comment]
Hi @tagomoris I have the same question, not sure how to run fluentd inside a container but still have it handle logging for containers on the host machine..?

**Comment by superdump** [comment]
You have to run the fluentd container with the json-file log driver.

Also, running fluentd in a container listening for syslog logs on a TCP port creates a situation where if the fluentd container is not running for some reason, docker will refuse to start other containers as the syslog log driver cannot initialise.

This felt too dangerous to me and I instead opted for using the json-file log driver with log rotation options set and using fluentd's file input, mapping /var/lib/docker/containers into the fluentd container.

**Comment by viztastic** [comment]
Hi @superdump is there an example I can refer to by any chance? Much appreciated.

**Comment by MrMMorris** [comment]
@superdump just as an FYI, a `fail-on-startup-error` log-opt has been added in 1.11 that will ignore fluentd being unreachable and allow you to start containers anyway:

https://github.com/jnummelin/docker/blob/3cf82ff1ab14e1ddd2b629524e894ac359168388/docs/admin/logging/fluentd.md#fail-on-startup-error

I have backported it to 1.9.1 and built my own docker binary because I don't have time to wait until 1.11 for a solution to such an obvious issue.
