### ISSUE TITLE
Environment variable name that specifies PATH in fluent.conf is different from fluentd side

### ISSUE THREAD

**Issue by Anorlondo448** [fluent/fluentd-docker-image#227]
in fluentd document, "FLUENT_CONF"
https://docs.fluentd.org/configuration/config-file#fluent_conf-environment-variable

```
FLUENT_CONF Environment Variable  
You can change the default configuration file location via FLUENT_CONF. For example, /etc/td-agent/td-agent.conf is specified via FLUENT_CONF inside td-agent scripts.  
```

but fluentd docker image, "FLUENTD_CONF"
```
set -- "$@" -c /fluentd/etc/${FLUENTD_CONF}
```

https://github.com/fluent/fluentd-docker-image/blob/c7ad87985d5d10f5369634e85e5bc75b8c3df760/v0.12/alpine/entrypoint.sh#L20

I want to use the same environment variable name

**Comment by ashie** [comment]
Won't fix, because each of them are for different users:

* `FLUENT_CONF`: Used by fluentd
* `FLUNENTD_CONF`: Used by entrypoint.sh

If `FLUENTD_CONF` is changed to `FLUENT_CONF`, it's referred by fluentd unexpectedly.
In fact, it should be changed to a completely different name like `FLUENTD_CONF_FILE_NAME` to avoid such misunderstanding, but it's not as serious problem as we really have to do it.
