### ISSUE TITLE
Fluentd v1.15 docker image should bundle XML library gem by default

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd-docker-image#344]
On upgrading Ruby version to 3.1, REXML is dropped from the default gems.
AWS related plugin such as fluent-plugin-opensearch and fluent-plugin-s3 are failed to start due to missing XML library gem such as REXML and nokogiri.

For lightweight dependencies, we should bundle REXML as XML library by default.
This issue is originally reported in: https://github.com/fluent/fluent-plugin-opensearch/issues/73#issuecomment-1249761041

**Comment by ashie** [comment]
I didn't include rexml gem intentionally since fluentd itself doesn't use it.
We shouldn't include unused gems into our Docker image basically.
But now I agree with you that it's better to include well used gems.
aws-sdk gem (which requires a XML library implicitly) is required in various inherited Docker images, so that it's troublesome to update them individually.

**Comment by cosmo0920** [comment]
Yup, we did break backward compatibility. Even if we don't include XML library, we have to add a note for XML library at least.
